### ISSUE TITLE
The subscription key is only for 2 million character translation

### ISSUE THREAD

**Issue by Jarvisss** [do-something-for-fun/thesis-helper#10]
If you are using the F0 free trial, the upbound would be 2000,000, and this is a fairly small amount for multiple users. Try using free translating APIs.

**Comment by Jarvisss** [comment]
Maybe an interface for user themselves adding keys would solve this problem, and by default using google translate or something.

**Comment by Jarvisss** [comment]
For google translation:
'''
def get_google_translation(text_input,language_output='zh-cn'):
&emsp;&emsp;translator = Translator(service_urls=['translate.google.cn'])
&emsp;&emsp;text = translator.translate(text_input, src='auto', dest=language_output).text
&emsp;&emsp;return text
&emsp;&emsp;pass
'''

**Comment by QSCTech-Sange** [comment]
Solved. 
It's now using Google Translation.
Thanks for your advice.
