### ISSUE TITLE
words sticky together

### ISSUE THREAD

**Issue by muhualing** [do-something-for-fun/thesis-helper#13]
As you see, the word, in the end, will stick with the beginning word in the next line.
![image](https://user-images.githubusercontent.com/12086605/68258449-b4a15d80-0071-11ea-9e40-1f19ef1de69d.png)
@QSCTech-Sange

**Comment by Jarvisss** [comment]
这个似乎是pdfjs处理的问题，换行符被吃了，目的是为了解决短横线的问题

**Comment by Jarvisss** [comment]
用google的免费翻译会有这个问题，用Azure的就不会，百度翻译和有道似乎也不会

**Comment by muhualing** [comment]
> 用google的免费翻译会有这个问题，用Azure的就不会，百度翻译和有道似乎也不会

是的，谷歌免费翻译不给力啊

**Comment by muhualing** [comment]
> 这个似乎是pdfjs处理的问题，换行符被吃了，目的是为了解决短横线的问题

嗯，不用自己写换行符了，以前写过一个先去换行符再用空格连起来。
现在出现的问题是就会有单词粘滞和短横线的问题，比如`con-ference`这种，句尾词和下一行新开头的词是一个词，但用了短横线。用`spellchecker`可以解决，就是速度太慢了。

**Comment by Jarvisss** [comment]
> > 这个似乎是pdfjs处理的问题，换行符被吃了，目的是为了解决短横线的问题
> 
> 嗯，不用自己写换行符了，以前写过一个先去换行符再用空格连起来。
> 现在出现的问题是就会有单词粘滞和短横线的问题，比如`con-ference`这种，句尾词和下一行新开头的词是一个词，但用了短横线。用`spellchecker`可以解决，就是速度太慢了。

单词粘滞不知道怎么解决，短横线提交了一个pr

**Comment by muhualing** [comment]
> > > 这个似乎是pdfjs处理的问题，换行符被吃了，目的是为了解决短横线的问题
> > 
> > 
> > 嗯，不用自己写换行符了，以前写过一个先去换行符再用空格连起来。
> > 现在出现的问题是就会有单词粘滞和短横线的问题，比如`con-ference`这种，句尾词和下一行新开头的词是一个词，但用了短横线。用`spellchecker`可以解决，就是速度太慢了。
> 
> 单词粘滞不知道怎么解决，短横线提交了一个pr

优秀啊，加你qq了

**Comment by QSCTech-Sange** [comment]
Solved. 
@Jarvisss @muhualing  
Thanks for your advice and contribution.
