### ISSUE TITLE
请导出requirements.txt

### ISSUE THREAD

**Issue by Lucas-Wye** [do-something-for-fun/thesis-helper#2]
采用 `pip freeze > requirements.txt` 来导出python依赖信息，不然各个版本不一致，无法运行成功

**Comment by muhualing** [comment]
好的

**Comment by muhualing** [comment]
pyperclip==1.7.0 PyQt5==5.13.1 PyQt5-sip==12.7.0 PyQtWebEngine==5.13.2 requests==2.22.0 
[requirements.txt](https://github.com/muhualing/thesis-helper/files/3806963/requirements.txt)

**Comment by Lucas-Wye** [comment]
thanks
