### ISSUE TITLE
QtWebEngineWidgets  not found, Win10 python 3.6 64bit

### ISSUE THREAD

**Issue by the-butterfly** [do-something-for-fun/thesis-helper#23]
PS E:\Software\PaperTools\thesis-helper> python .\thesis-helper.py                                                                 Traceback (most recent call last):
  File ".\thesis-helper.py", line 9, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
PS E:\Software\PaperTools\thesis-helper> python -V                                                                                 Python 3.6.3 :: Anaconda custom (64-bit)
PS E:\Software\PaperTools\thesis-helper> pip show pyqt5                                                                            Name: PyQt5
Version: 5.13.2
Summary: Python bindings for the Qt cross platform UI and application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: c:\software\anaconda3\lib\site-packages
Requires: PyQt5-sip
Required-by: PyQtWebEngine
PS E:\Software\PaperTools\thesis-helper>

**Comment by Jarvisss** [comment]
pip install PyQtWebEngine

**Comment by the-butterfly** [comment]
@Jarvisss 测试时已经安装了，无效；
将PyQt5回滚到 5.10.1 版本，问题可解决。

**Comment by Jarvisss** [comment]
> @Jarvisss 测试时已经安装了，无效；
> 将PyQt5回滚到 5.10.1 版本，问题可解决。
我遇到过这个问题，pip install PyQtWebEngine可以解决，如果已经安装，可以先pip uninstall 再pip install
