### ISSUE TITLE
Collapse while the words are copied.

### ISSUE THREAD

**Issue by ICMoon527** [do-something-for-fun/thesis-helper#36]
![image](https://user-images.githubusercontent.com/44260376/68391198-fe896100-01a1-11ea-857d-23f156acb5fe.png)

**Comment by Jarvisss** [comment]
What's your platform? 
And please provide the details how it collapsed, it will help us fix it

**Comment by ICMoon527** [comment]
platform: Windows
collapse after right clicking the selected part
![image](https://user-images.githubusercontent.com/44260376/68452837-a9476100-022e-11ea-8908-14a056cdecee.png)

**Comment by QSCTech-Sange** [comment]
You can revise this line into 
```
if e.type() == QEvent.ChildRemoved and e.child().isWidgetType():
```
just add a `()` behind `child`.
It's an old bug and has been fixed, but not in our release version.
