### ISSUE TITLE
Little advice

### ISSUE THREAD

**Issue by dendenxu** [do-something-for-fun/thesis-helper#4]
I've developed a similar program for similar reasons.
However, the translation API blocks your IP address after several translation attempts.
This also happens when you use translate.googleapi.com or translate.google.cn.
Haven't tested for baidu translator.

My advice is, use your web browser to do the translation.
May end up with a better look right?
My try is here(using chrome): https://github.com/dendenxu/Chrome-Based-Thesis-Translator

**Comment by QSCTech-Sange** [comment]
I found the problem too. Your advice is a cool approach.

**Comment by QSCTech-Sange** [comment]
Solved. 
It's now using Google Translation.
Thanks for your advice.
