### ISSUE TITLE
googletrans.compat模块不存问题以及修改建议

### ISSUE THREAD

**Issue by Dongzhixiao** [do-something-for-fun/thesis-helper#45]
- 出现问题：googletrans.compat模块不存在
- 问题原因：通过`pip install -r requirements.txt`安装包文件，如果未指定版本，会默认安装最新版本。而googletrans此时(2020.6.16)已是3.0.0版本，里面googletrans.compat模块已移除。
- 解决方案：googletrans包通过指定版本安装——`pip install googletrans=2.4.0`
- 结论：建议修改requirements.txt文件，在里面加入包的版本号。

**Comment by ICMoon527** [comment]
Awesome! 
And `pip install googletrans==2.4.0`
